development:
  adapter: postgresql
  encoding: utf8
  database: philly-open-health_development
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: philly-open-health_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: philly-open-health_production
  pool: 5
  username: 
  password: